#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-pdf-inspector
Version  : 1.2.0
Release  : 5
URL      : https://rubygems.org/downloads/pdf-inspector-1.2.0.gem
Source0  : https://rubygems.org/downloads/pdf-inspector-1.2.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : Ruby
BuildRequires : ruby
BuildRequires : rubygem-rdoc

%description
# PDF::Inspector : A tool for analyzing PDF output
This library provides a number of [PDF::Reader][0] based tools for use in testing
PDF output.  Presently, the primary purpose of this tool is to support the
tests found in [Prawn][1], a pure Ruby PDF generation library.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n pdf-inspector-1.2.0
gem spec %{SOURCE0} -l --ruby > rubygem-pdf-inspector.gemspec

%build
gem build rubygem-pdf-inspector.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
pdf-inspector-1.2.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/pdf-inspector-1.2.0.gem
/usr/lib64/ruby/gems/2.3.0/gems/pdf-inspector-1.2.0/CHANGELOG
/usr/lib64/ruby/gems/2.3.0/gems/pdf-inspector-1.2.0/COPYING
/usr/lib64/ruby/gems/2.3.0/gems/pdf-inspector-1.2.0/GPLv2
/usr/lib64/ruby/gems/2.3.0/gems/pdf-inspector-1.2.0/GPLv3
/usr/lib64/ruby/gems/2.3.0/gems/pdf-inspector-1.2.0/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/pdf-inspector-1.2.0/README.md
/usr/lib64/ruby/gems/2.3.0/gems/pdf-inspector-1.2.0/lib/pdf/inspector.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-inspector-1.2.0/lib/pdf/inspector/extgstate.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-inspector-1.2.0/lib/pdf/inspector/graphics.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-inspector-1.2.0/lib/pdf/inspector/page.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-inspector-1.2.0/lib/pdf/inspector/text.rb
/usr/lib64/ruby/gems/2.3.0/gems/pdf-inspector-1.2.0/lib/pdf/inspector/xobject.rb
/usr/lib64/ruby/gems/2.3.0/specifications/pdf-inspector-1.2.0.gemspec
